name: Issues

on:
  issues:
    types: [labeled]

permissions:
  issues: write

jobs:
  help-wanted:
    if: github.event.label.name == 'help wanted'
    runs-on: ubuntu-latest
    steps:
      - name: Add comment
        uses: actions/github-script@v7
        with:
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "Thank you for your question! We will consider it shortly."
            })
